import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navbar
    nav_dashboard: 'Dashboard',
    nav_report: 'Report Issue',
    nav_signout: 'Sign out',
    nav_signin: 'Sign In',
    nav_register: 'Register',
    nav_portal: 'Government Issue Portal',

    // Login
    login_title: 'Portal Sign In',
    login_subtitle: 'Select your role, then enter your credentials',
    login_as: 'I am signing in as',
    login_email: 'Email Address',
    login_password: 'Password',
    login_btn: 'Sign In as',
    login_signing: 'Signing in…',
    login_new_citizen: 'New citizen?',
    login_register_here: 'Register here →',
    login_credentials_note: 'credentials are issued privately by the system administrator.',
    login_left_title: 'Civic Issue Reporting & Resolution System',
    login_left_sub: 'An integrated digital platform enabling citizens to report public infrastructure issues and government departments to manage resolutions efficiently and transparently.',
    login_who: 'Who uses this portal?',
    login_footer: 'Government of India · Digital Governance Initiative',
    role_citizen: 'Citizen',
    role_citizen_desc: 'Report & track issues',
    role_citizen_hint: 'Register for a free citizen account to submit complaints and track their resolution in real-time.',
    role_department: 'Department',
    role_dept_desc: 'Manage complaints',
    role_dept_hint: 'Use the official departmental email address issued to you by the system administrator.',
    role_admin: 'Admin',
    role_admin_desc: 'System management',
    role_admin_hint: 'Restricted access. For authorised system administrators only.',
    login_feat1: 'AI-powered issue categorisation & routing',
    login_feat2: 'Real-time complaint status tracking',
    login_feat3: 'Geolocation-tagged submissions',
    login_feat4: 'Multi-department workflow management',
    login_feat5: 'Citizen feedback & satisfaction scoring',

    // Register
    reg_title: 'Citizen Registration',
    reg_subtitle: 'Create your account to report civic issues',
    reg_name: 'Full Name',
    reg_email: 'Email Address',
    reg_phone: 'Phone Number',
    reg_password: 'Password',
    reg_confirm: 'Confirm Password',
    reg_btn: '→  Register as Citizen',
    reg_loading: 'Creating account…',
    reg_have_account: 'Already registered?',
    reg_signin: 'Sign in →',
    reg_left_title: 'Join the Civic Reporting Network',
    reg_left_sub: 'Register as a citizen to report public infrastructure issues directly to the responsible government department.',
    reg_feat1: 'Submit photo-evidenced complaints',
    reg_feat2: 'Automatic GPS location tagging',
    reg_feat3: 'Track resolution progress live',
    reg_feat4: 'Rate department responses',
    reg_feat5: 'Help improve public services',

    // Citizen Dashboard
    cd_banner_label: 'Citizen Dashboard',
    cd_banner_sub: 'Track and manage your submitted civic complaints',
    cd_welcome: 'Welcome,',
    cd_report_btn: '+ Report New Issue',
    cd_stat_total: 'Total Submitted',
    cd_stat_pending: 'Pending Review',
    cd_stat_progress: 'In Progress',
    cd_stat_resolved: 'Resolved',
    cd_tab_all: 'All Complaints',
    cd_empty_title: 'No complaints submitted yet',
    cd_empty_none: 'No complaints',
    cd_empty_desc: 'Help improve your city by reporting public issues.',
    cd_empty_btn: 'Report Your First Issue',

    // Department Dashboard
    dd_banner_label: 'Department Portal',
    dd_banner_sub: 'Manage and resolve assigned complaints',
    dd_stat_total: 'Total Assigned',
    dd_stat_pending: 'Pending',
    dd_stat_progress: 'In Progress',
    dd_stat_resolved: 'Resolved',
    dd_stat_reopened: 'Reopened',
    dd_stat_feedback: 'Feedback Avg',
    dd_emergency: 'Emergency complaint',
    dd_emergency_plural: 'Emergency complaints',
    dd_emergency_suffix: 'require immediate attention.',
    dd_tab_all: 'All',
    dd_empty_title: 'All clear!',
    dd_empty_desc: 'No complaints at this time.',
    dd_avg_rating: 'Avg. Rating',

    // Submit Complaint
    sc_title: 'Report a Civic Issue',
    sc_subtitle: 'Describe the problem clearly — our AI will categorise and route it automatically.',
    sc_ai_title: '🤖 AI-Powered Routing',
    sc_ai_desc: 'Your complaint will be automatically categorised (Roads, Drainage, Electrical, Sanitation) and prioritised, then routed directly to the responsible department.',
    sc_section_details: '📋 Complaint Details',
    sc_issue_title: 'Issue Title *',
    sc_title_ph: 'e.g. Large pothole near bus stand on MG Road',
    sc_title_hint: 'Be specific — include the landmark or road name.',
    sc_desc: 'Detailed Description *',
    sc_desc_ph: 'Describe the issue in detail — what is the problem, how long has it existed, does it pose a safety risk?',
    sc_desc_hint: 'Minimum 5 words. More detail helps departments resolve issues faster.',
    sc_section_photo: '📸 Photo Evidence',
    sc_upload: '🖼 Upload File',
    sc_webcam: '📷 Use Live Webcam',
    sc_drop: 'Click to upload or drag & drop',
    sc_drop_sub: 'JPG, PNG — max 10 MB',
    sc_recapture: '📷 Recapture with Webcam',
    sc_remove: '✕ Remove',
    sc_section_location: '📍 Location',
    sc_address: 'Address / Landmark',
    sc_address_ph: 'e.g. Near Gandhi Market, Coimbatore',
    sc_gps_btn: '📍 Capture GPS Coordinates',
    sc_gps_loading: '⏳ Getting location…',
    sc_gps_captured: 'GPS captured:',
    sc_submit_btn: '📤  Submit Complaint to Government Portal',
    sc_submitting: 'Submitting…',

    // Complaint Card
    cc_view: 'View Details →',
    cc_dept: 'Dept:',
    cc_submitted: 'Submitted',

    // Complaint Detail
    detail_back: '← Back',
    detail_dept: 'Department',
    detail_confidence: 'ML Confidence',
    detail_submitted: 'Submitted',
    detail_reporter: 'Reported by',
    detail_photo: '📸 Photo Evidence',
    detail_location: '📍 Location',
    detail_maps: '🗺️ View on Map',
    detail_update_status: 'Update Status',
    detail_note_ph: 'Add a note (optional)',
    detail_update_btn: 'Update Status',
    detail_updating: 'Saving…',
    detail_feedback_title: '⭐ Rate This Resolution',
    detail_feedback_hint: 'How satisfied are you with how this was resolved?',
    detail_feedback_comment: 'Comments (optional)',
    detail_feedback_ph: 'Share your experience…',
    detail_feedback_btn: 'Submit Feedback',
    detail_feedbacks: '💬 Citizen Feedback',
    detail_history: '📋 Activity History',
    detail_reopened: 'Reopened',
    detail_times: 'time(s)',
    detail_triggered: '⚠️ Triggered complaint reopen',

    // Admin
    admin_title: 'Admin Dashboard',
    admin_sub: 'System-wide analytics and complaint management',
    admin_total: 'Total Complaints',
    admin_pending: 'Pending',
    admin_progress: 'In Progress',
    admin_resolved: 'Resolved',
    admin_reopened: 'Reopened',
    admin_avg: 'Avg Rating',
    admin_tab_overview: 'Overview',
    admin_tab_complaints: 'All Complaints',
    admin_tab_feedback: 'Feedback',

    // Common
    status_pending: 'Pending',
    status_progress: 'In Progress',
    status_completed: 'Completed',
    status_reopened: 'Reopened',
    priority_emergency: 'Emergency',
    priority_high: 'High',
    priority_medium: 'Medium',
    priority_low: 'Low',
    loading: 'Loading…',
    lang_toggle: 'தமிழ்',
  },

  ta: {
    // Navbar
    nav_dashboard: 'டாஷ்போர்டு',
    nav_report: 'புகார் தெரிவி',
    nav_signout: 'வெளியேறு',
    nav_signin: 'உள்நுழை',
    nav_register: 'பதிவு செய்',
    nav_portal: 'அரசு புகார் மேடை',

    // Login
    login_title: 'மேடையில் உள்நுழைய',
    login_subtitle: 'உங்கள் பங்கை தேர்ந்தெடுத்து உள்நுழையவும்',
    login_as: 'நான் உள்நுழைவது',
    login_email: 'மின்னஞ்சல் முகவரி',
    login_password: 'கடவுச்சொல்',
    login_btn: 'உள்நுழை',
    login_signing: 'உள்நுழைகிறது…',
    login_new_citizen: 'புதிய குடிமகனா?',
    login_register_here: 'இங்கே பதிவு செய் →',
    login_credentials_note: 'நற்சான்றிதழ்கள் நிர்வாகியால் வழங்கப்படும்.',
    login_left_title: 'குடிமை புகார் & தீர்வு மேடை',
    login_left_sub: 'குடிமக்கள் பொது உள்கட்டமைப்பு சிக்கல்களை புகாரளிக்கவும், அரசு துறைகள் தீர்வுகளை நிர்வகிக்கவும் உதவும் ஒருங்கிணைந்த டிஜிட்டல் தளம்.',
    login_who: 'இந்த மேடையை யார் பயன்படுத்துவார்கள்?',
    login_footer: 'இந்திய அரசு · டிஜிட்டல் நிர்வாக முயற்சி',
    role_citizen: 'குடிமகன்',
    role_citizen_desc: 'புகார் & கண்காணிப்பு',
    role_citizen_hint: 'புகார்களை சமர்ப்பிக்கவும் நிகழ்நேரத்தில் கண்காணிக்கவும் இலவச குடிமகன் கணக்கை பதிவு செய்யவும்.',
    role_department: 'துறை',
    role_dept_desc: 'புகார்களை நிர்வகி',
    role_dept_hint: 'நிர்வாகி வழங்கிய அதிகாரப்பூர்வ துறை மின்னஞ்சலைப் பயன்படுத்தவும்.',
    role_admin: 'நிர்வாகி',
    role_admin_desc: 'கணினி மேலாண்மை',
    role_admin_hint: 'கட்டுப்படுத்தப்பட்ட அணுகல். அங்கீகரிக்கப்பட்ட நிர்வாகிகளுக்கு மட்டுமே.',
    login_feat1: 'AI-இயக்கப்படும் வகைப்படுத்தல் & வழிகாட்டல்',
    login_feat2: 'நிகழ்நேர புகார் நிலை கண்காணிப்பு',
    login_feat3: 'GPS இருப்பிட குறியீட்டு சமர்ப்பிப்புகள்',
    login_feat4: 'பல துறை பணிப்பாய்வு மேலாண்மை',
    login_feat5: 'குடிமகன் கருத்து & திருப்தி மதிப்பீடு',

    // Register
    reg_title: 'குடிமகன் பதிவு',
    reg_subtitle: 'குடிமை சிக்கல்களை புகாரளிக்க கணக்கை உருவாக்கவும்',
    reg_name: 'முழு பெயர்',
    reg_email: 'மின்னஞ்சல் முகவரி',
    reg_phone: 'தொலைபேசி எண்',
    reg_password: 'கடவுச்சொல்',
    reg_confirm: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    reg_btn: '→  குடிமகனாக பதிவு செய்',
    reg_loading: 'கணக்கை உருவாக்குகிறது…',
    reg_have_account: 'ஏற்கனவே பதிவு செய்தீர்களா?',
    reg_signin: 'உள்நுழை →',
    reg_left_title: 'குடிமை புகார் வலையமைப்பில் சேரவும்',
    reg_left_sub: 'பொது உள்கட்டமைப்பு சிக்கல்களை நேரடியாக பொறுப்பான அரசு துறைக்கு புகாரளிக்க குடிமகனாக பதிவு செய்யவும்.',
    reg_feat1: 'புகைப்பட சான்றுடன் புகார் சமர்ப்பி',
    reg_feat2: 'தானியங்கி GPS இருப்பிட குறியீடு',
    reg_feat3: 'தீர்வு முன்னேற்றத்தை நேரடியாக கண்காணி',
    reg_feat4: 'துறை பதில்களை மதிப்பிடு',
    reg_feat5: 'பொது சேவைகளை மேம்படுத்த உதவு',

    // Citizen Dashboard
    cd_banner_label: 'குடிமகன் டாஷ்போர்டு',
    cd_banner_sub: 'சமர்ப்பித்த புகார்களை கண்காணி & நிர்வகி',
    cd_welcome: 'வணக்கம்,',
    cd_report_btn: '+ புதிய புகார் தெரிவி',
    cd_stat_total: 'மொத்தம் சமர்ப்பித்தவை',
    cd_stat_pending: 'நிலுவையில் உள்ளவை',
    cd_stat_progress: 'செயலில் உள்ளவை',
    cd_stat_resolved: 'தீர்க்கப்பட்டவை',
    cd_tab_all: 'அனைத்து புகார்கள்',
    cd_empty_title: 'இதுவரை புகார் சமர்ப்பிக்கவில்லை',
    cd_empty_none: 'புகார்கள் இல்லை',
    cd_empty_desc: 'பொது சிக்கல்களை புகாரளிப்பதன் மூலம் உங்கள் நகரை மேம்படுத்துங்கள்.',
    cd_empty_btn: 'முதல் புகாரை தெரிவிக்கவும்',

    // Department Dashboard
    dd_banner_label: 'துறை மேடை',
    dd_banner_sub: 'ஒதுக்கப்பட்ட புகார்களை நிர்வகி & தீர்',
    dd_stat_total: 'மொத்தம் ஒதுக்கப்பட்டவை',
    dd_stat_pending: 'நிலுவை',
    dd_stat_progress: 'செயலில்',
    dd_stat_resolved: 'தீர்க்கப்பட்டது',
    dd_stat_reopened: 'மீண்டும் திறக்கப்பட்டது',
    dd_stat_feedback: 'சராசரி மதிப்பீடு',
    dd_emergency: 'அவசர புகார்',
    dd_emergency_plural: 'அவசர புகார்கள்',
    dd_emergency_suffix: 'உடனடி கவனம் தேவை.',
    dd_tab_all: 'அனைத்தும்',
    dd_empty_title: 'அனைத்தும் சரி!',
    dd_empty_desc: 'இப்போது புகார்கள் இல்லை.',
    dd_avg_rating: 'சராசரி மதிப்பீடு',

    // Submit Complaint
    sc_title: 'குடிமை புகார் தெரிவி',
    sc_subtitle: 'சிக்கலை தெளிவாக விவரிக்கவும் — AI தானியங்கியாக வகைப்படுத்தி வழிகாட்டும்.',
    sc_ai_title: '🤖 AI வழிகாட்டல்',
    sc_ai_desc: 'உங்கள் புகார் தானியங்கியாக வகைப்படுத்தப்பட்டு (சாலை, வடிகால், மின்சாரம், சுகாதாரம்) முன்னுரிமை அளிக்கப்பட்டு பொறுப்பான துறைக்கு அனுப்பப்படும்.',
    sc_section_details: '📋 புகார் விவரங்கள்',
    sc_issue_title: 'புகார் தலைப்பு *',
    sc_title_ph: 'எ.கா. MG சாலையில் பேருந்து நிலையம் அருகே பெரிய குழி',
    sc_title_hint: 'குறிப்பிட்டுக் கூறுங்கள் — அடையாளமதிப்பு அல்லது சாலை பெயரை சேர்க்கவும்.',
    sc_desc: 'விரிவான விவரம் *',
    sc_desc_ph: 'சிக்கலை விரிவாக விவரிக்கவும் — என்ன பிரச்சனை, எவ்வளவு நாட்களாக இருக்கிறது, பாதுகாப்பு அபாயம் உள்ளதா?',
    sc_desc_hint: 'குறைந்தது 5 வார்த்தைகள். அதிக விவரம் துறைகள் விரைவாக தீர்க்க உதவும்.',
    sc_section_photo: '📸 புகைப்பட சான்று',
    sc_upload: '🖼 கோப்பு பதிவேற்று',
    sc_webcam: '📷 நேரடி கேமரா பயன்படுத்து',
    sc_drop: 'கிளிக் செய்து பதிவேற்றவும் அல்லது இழுத்து விடவும்',
    sc_drop_sub: 'JPG, PNG — அதிகபட்சம் 10 MB',
    sc_recapture: '📷 மீண்டும் எடு',
    sc_remove: '✕ நீக்கு',
    sc_section_location: '📍 இருப்பிடம்',
    sc_address: 'முகவரி / அடையாளம்',
    sc_address_ph: 'எ.கா. காந்தி மார்க்கட் அருகே, கோயம்புத்தூர்',
    sc_gps_btn: '📍 GPS ஆயத்தொகுப்புகளை பதிவு செய்',
    sc_gps_loading: '⏳ இருப்பிடம் கண்டறிகிறது…',
    sc_gps_captured: 'GPS பதிவு செய்யப்பட்டது:',
    sc_submit_btn: '📤  அரசு மேடைக்கு புகார் சமர்ப்பி',
    sc_submitting: 'சமர்ப்பிக்கிறது…',

    // Complaint Card
    cc_view: 'விவரங்கள் காண →',
    cc_dept: 'துறை:',
    cc_submitted: 'சமர்ப்பிக்கப்பட்டது',

    // Complaint Detail
    detail_back: '← திரும்பு',
    detail_dept: 'துறை',
    detail_confidence: 'ML நம்பகத்தன்மை',
    detail_submitted: 'சமர்ப்பித்த தேதி',
    detail_reporter: 'புகாரளித்தவர்',
    detail_photo: '📸 புகைப்பட சான்று',
    detail_location: '📍 இருப்பிடம்',
    detail_maps: '🗺️ வரைபடத்தில் காண',
    detail_update_status: 'நிலையை புதுப்பி',
    detail_note_ph: 'குறிப்பு சேர்க்கவும் (விருப்பமானது)',
    detail_update_btn: 'நிலையை புதுப்பி',
    detail_updating: 'சேமிக்கிறது…',
    detail_feedback_title: '⭐ தீர்வை மதிப்பிடு',
    detail_feedback_hint: 'இந்த தீர்வில் நீங்கள் எவ்வளவு திருப்தி அடைந்தீர்கள்?',
    detail_feedback_comment: 'கருத்துகள் (விருப்பமானது)',
    detail_feedback_ph: 'உங்கள் அனுபவத்தை பகிரவும்…',
    detail_feedback_btn: 'கருத்தை சமர்ப்பி',
    detail_feedbacks: '💬 குடிமகன் கருத்துகள்',
    detail_history: '📋 செயல் வரலாறு',
    detail_reopened: 'மீண்டும் திறக்கப்பட்டது',
    detail_times: 'முறை',
    detail_triggered: '⚠️ புகார் மீண்டும் திறக்கப்பட்டது',

    // Admin
    admin_title: 'நிர்வாக டாஷ்போர்டு',
    admin_sub: 'கணினி அளவிலான பகுப்பாய்வு மற்றும் புகார் மேலாண்மை',
    admin_total: 'மொத்த புகார்கள்',
    admin_pending: 'நிலுவை',
    admin_progress: 'செயலில்',
    admin_resolved: 'தீர்க்கப்பட்டது',
    admin_reopened: 'மீண்டும் திறக்கப்பட்டது',
    admin_avg: 'சராசரி மதிப்பீடு',
    admin_tab_overview: 'கண்ணோட்டம்',
    admin_tab_complaints: 'அனைத்து புகார்கள்',
    admin_tab_feedback: 'கருத்துகள்',

    // Common
    status_pending: 'நிலுவை',
    status_progress: 'செயலில்',
    status_completed: 'தீர்க்கப்பட்டது',
    status_reopened: 'மீண்டும் திறக்கப்பட்டது',
    priority_emergency: 'அவசரம்',
    priority_high: 'அதிக முன்னுரிமை',
    priority_medium: 'நடுத்தர முன்னுரிமை',
    priority_low: 'குறைந்த முன்னுரிமை',
    loading: 'ஏற்றுகிறது…',
    lang_toggle: 'English',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = (key) => translations[lang][key] || translations['en'][key] || key;
  const toggleLang = () => setLang(l => l === 'en' ? 'ta' : 'en');
  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
